Fixed all broken links in landing README
bwhm/joystream-content-system pull request #1
Opened 2019-11-17 09:13 UTC by blrhc

Required making new `class` markdown file, followed Martin's template but may need to be corrected...

2019-11-18 16:56 UTC, bwhm requested changes
When/if you have time, feel free to update the `video` and `music` class.md docs as well :)

2019-11-18 16:56 UTC, bwhm commented on classes/general/featured-content.md
> +##### In Class index 0
The idea here is to show the `properties` by their `in_class_index`, so these should count from 0-2.

Do you mind fixing that?

2019-11-18 16:56 UTC, bwhm commented on classes/general/featured-content.md
> +## Entities
Not all classes will have "fixed" entities, so you can delete this here...

2019-11-18 19:52 UTC, blrhc commented
> When/if you have time, feel free to update the `video` and `music` class.md docs as well :)

Will do this ASAP.

2019-11-19 09:13 UTC, bwhm approved these changes

2019-11-19 09:14 UTC, merged